govulncheck requires Go 1.26.0
```
Run go install golang.org/x/vuln/cmd/govulncheck@latest
go: downloading golang.org/x/vuln v1.8.0
go: golang.org/x/vuln/cmd/govulncheck@latest: golang.org/x/vuln@v1.8.0 requires go >= 1.26.0 (running go 1.25.13; GOTOOLCHAIN=local)
Error: Process completed with exit code 1.
```

Close #210