[GO-2025-3749][GO-2025-3750] Requires Go 1.24.4
```
=== Symbol Results ===

Vulnerability #1: GO-2025-3750
    Inconsistent handling of O_CREATE|O_EXCL on Unix and Windows in os in
    syscall
  More info: https://pkg.go.dev/vuln/GO-2025-3750
  Standard library
    Found in: os@go1.24
    Fixed in: os@go1.24.4
    Platforms: windows
    Example traces found:
Error:       #1: run_requests.go:8:2: funnel_http.init calls http.init, which eventually calls os.NewFile
Error:       #2: run_requests.go:5:2: funnel_http.init calls errors.init, which eventually calls os.Open
Error:       #3: run_requests.go:8:2: funnel_http.init calls http.init, which eventually calls os.ReadDir
Error:       #4: run_requests.go:8:2: funnel_http.init calls http.init, which eventually calls os.ReadFile
Error:       #5: run_requests.go:5:2: funnel_http.init calls errors.init, which eventually calls os.Stat
Error:       #6: run_requests.go:8:2: funnel_http.init calls http.init, which eventually calls syscall.Open

Vulnerability #2: GO-2025-3749
    Usage of ExtKeyUsageAny disables policy validation in crypto/x509
  More info: https://pkg.go.dev/vuln/GO-2025-3749
  Standard library
    Found in: crypto/x509@go1.24
    Fixed in: crypto/x509@go1.24.4
    Example traces found:
Error:       #1: run_requests.go:8:2: funnel_http.init calls http.init, which eventually calls x509.Certificate.Verify

Your code is affected by 2 vulnerabilities from the Go standard library.
This scan also found 3 vulnerabilities in packages you import and 1
vulnerability in modules you require, but your code doesn't appear to call these
vulnerabilities.
Use '-show verbose' for more details.
Error: Process completed with exit code 3.
```