Requires Go 1.25.8
```
=== Symbol Results ===

Vulnerability #1: GO-2026-4602
    FileInfo can escape from a Root in os
  More info: https://pkg.go.dev/vuln/GO-2026-4602
  Standard library
    Found in: os@go1.25
    Fixed in: os@go1.25.8
    Example traces found:
Error:       #1: run_requests.go:8:2: funnel_http.init calls http.init, which eventually calls os.ReadDir
```

https://github.com/sue445/funnel_http/actions/runs/23099799804/job/67098440108?pr=165